version: '3.8'
services:
    database:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - database-volume:/var/lib/postgresql/data

    nginx-reverse-proxy:
        build: nginx
        restart: always
        ports:
            - 8080:8080

    frontend:
        build: web
        restart: always
        depends_on:
            - nginx-reverse-proxy

    backend:
        build: 
            dockerfile: Dockerfile
            context: ./backend
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - nginx-reverse-proxy
            - database

volumes:
  database-volume:
    driver: local
